#!/bin/bash
echo "🔍 Lambda Troubleshooting Guide"
echo "================================"
echo ""
echo "Current API Status:"
curl -s -w "\nHTTP Status: %{http_code}\n" "https://bhg1kt9cf2.execute-api.eu-central-1.amazonaws.com/prod/api/groups" -H "x-api-key: Y1leD4smWeX3yfCRM9Sv8R1Jo7g9zusx08Xo4y7o"
echo ""
echo "✅ 1. Fresh zip file created: minimal_lambda_fresh.zip"
echo ""
echo "📋 CRITICAL CHECKS IN AWS LAMBDA CONSOLE:"
echo "==========================================="
echo ""
echo "🔧 Function: uhabits-dashboard-api"
echo "   Go to: https://eu-central-1.console.aws.amazon.com/lambda/home?region=eu-central-1#/functions/uhabits-dashboard-api"
echo ""
echo "1️⃣  HANDLER SETTING (Most Common Issue!):"
echo "   - Go to 'Runtime settings' section"
echo "   - Handler MUST be: minimal_api.lambda_handler"
echo "   - NOT: lambda_function.lambda_handler"
echo "   - NOT: index.handler"
echo ""
echo "2️⃣  TIMEOUT SETTING:"
echo "   - Go to 'Configuration' → 'General configuration'"
echo "   - Timeout: 30 seconds (not 3 seconds!)"
echo "   - Memory: 256 MB"
echo ""
echo "3️⃣  CODE DEPLOYMENT:"
echo "   - Upload: minimal_lambda_fresh.zip"
echo "   - Click 'Deploy' after upload"
echo "   - Wait for 'Successfully updated the function' message"
echo ""
echo "4️⃣  TEST THE FUNCTION:"
echo "   - Go to 'Test' tab"
echo "   - Create new test event:"
echo '   {"httpMethod": "GET", "path": "/api/groups"}'
echo "   - Click 'Test'"
echo "   - Should return Status 200, not error"
echo ""
echo "5️⃣  CHECK CLOUDWATCH LOGS:"
echo "   - Go to 'Monitor' → 'View CloudWatch logs'"
echo "   - Look for recent errors"
echo "   - Should see: 'Received request:' and '✅ Returning mock data'"
echo ""
echo "🚨 COMMON ISSUES:"
echo "=================="
echo "• Handler wrong: minimal_api.lambda_handler"
echo "• Timeout too low: Must be 30+ seconds"
echo "• Code not deployed: Click 'Deploy' after upload"
echo "• Cache issue: Wait 2-3 minutes after deployment"
echo ""
echo "🧪 AFTER FIXING, TEST AGAIN:"
curl -s "https://bhg1kt9cf2.execute-api.eu-central-1.amazonaws.com/prod/api/groups" -H "x-api-key: Y1leD4smWeX3yfCRM9Sv8R1Jo7g9zusx08Xo4y7o" | jq '.summary.total_habits_analyzed // "Still broken"'
