#!/bin/bash

echo "🚨 LAMBDA 502 ERROR - EMERGENCY FIX"
echo "=================================="
echo ""
echo "Current API Status:"
curl -s -w "HTTP Status: %{http_code}\n" "https://bhg1kt9cf2.execute-api.eu-central-1.amazonaws.com/prod/api/groups" -H "x-api-key: Y1leD4smWeX3yfCRM9Sv8R1Jo7g9zusx08Xo4y7o"
echo ""
echo "🔧 IMMEDIATE FIX:"
echo "1. Upload: safe_lambda.zip (1.9KB)"
echo "2. Handler: safe_api.lambda_handler" 
echo "3. Deploy"
echo ""
echo "✅ WHAT THIS FIXES:"
echo "• Handles DynamoDB permission errors gracefully"
echo "• Won't crash if boto3 has issues"
echo "• Returns data even if DynamoDB fails"
echo "• Provides detailed logging for debugging"
echo ""
echo "📊 EXPECTED RESULT:"
echo "• If DynamoDB works: Shows real data (limited)"
echo "• If DynamoDB fails: Shows fallback mock data"
echo "• No more 502 errors!"
echo ""
echo "🧪 TEST AFTER UPLOAD:"
echo "curl -s 'https://bhg1kt9cf2.execute-api.eu-central-1.amazonaws.com/prod/api/groups' -H 'x-api-key: Y1leD4smWeX3yfCRM9Sv8R1Jo7g9zusx08Xo4y7o' | jq '.summary.data_source'"
echo ""
