#!/bin/bash

echo "=== FIXING API ENDPOINT ISSUE ==="
echo ""
echo "Problem identified:"
echo "- Dashboard was trying to use: bhg1kt9cf2.execute-api.eu-central-1.amazonaws.com" 
echo "- But the correct API Gateway is: jodcprzip3.execute-api.eu-central-1.amazonaws.com"
echo ""
echo "Solutions applied:"
echo "1. ✅ Fixed dashboard to use correct API endpoint"  
echo "2. ✅ Added missing API key header"
echo ""
echo "NEXT STEPS:"
echo ""
echo "Option A: Create new Lambda function for analytics"
echo "==========================================="
echo "1. Go to AWS Lambda Console"
echo "2. Create new function: 'uhabits-analytics'"
echo "3. Upload: minimal_lambda.zip"
echo "4. Set handler: minimal_api.lambda_handler"
echo "5. Set timeout: 30 seconds, memory: 256 MB"
echo "6. Go to API Gateway Console"
echo "7. Find API: jodcprzip3 (uhabits-api-prod)"
echo "8. Create new resource: /api/groups"
echo "9. Add GET method linked to uhabits-analytics function"
echo "10. Deploy to 'prod' stage"
echo ""
echo "Option B: Use existing function with new endpoint"
echo "=============================================="
echo "If uhabits-dashboard-api function exists on different gateway:"
echo "1. Find the correct API Gateway ID for dashboard API"
echo "2. Update dashboard to use that endpoint"
echo ""

# Test the corrected endpoint
echo "TESTING CORRECTED ENDPOINT:"
curl -s -w "HTTP Status: %{http_code}\n" -H "x-api-key: Y1leD4smWeX3yfCRM9Sv8R1Jo7g9zusx08Xo4y7o" "https://jodcprzip3.execute-api.eu-central-1.amazonaws.com/prod/api/groups"

echo ""
echo "If this returns 403 'Missing Authentication Token', the /api/groups endpoint"
echo "doesn't exist yet and needs to be created in API Gateway."
