#!/bin/bash

echo "=== LAMBDA DEPLOYMENT VERIFICATION ==="
echo ""
echo "You deployed minimal_lambda.zip but still getting 502 errors."
echo "This means one of these configuration issues:"
echo ""
echo "1. HANDLER NOT UPDATED"
echo "   Current: simple_dashboard_api.lambda_handler"
echo "   Required: minimal_api.lambda_handler"
echo ""
echo "2. TIMEOUT TOO LOW"
echo "   Current: 3 seconds"
echo "   Required: 30 seconds"
echo ""
echo "3. MEMORY TOO LOW"
echo "   Current: 128 MB"
echo "   Required: 256 MB"
echo ""
echo "=== STEP-BY-STEP FIX ==="
echo ""
echo "Go to AWS Lambda Console:"
echo "1. Find function: uhabits-dashboard-api"
echo "2. Code tab → Runtime settings → Edit"
echo "3. Change Handler to: minimal_api.lambda_handler"
echo "4. Configuration tab → General configuration → Edit"
echo "5. Set Timeout: 30 seconds"
echo "6. Set Memory: 256 MB"
echo "7. Save all changes"
echo ""
echo "=== TEST AFTER CHANGES ==="
echo 'curl -H "x-api-key: Y1leD4smWeX3yfCRM9Sv8R1Jo7g9zusx08Xo4y7o" "https://bhg1kt9cf2.execute-api.eu-central-1.amazonaws.com/prod/api/groups"'
echo ""
echo "Expected: HTTP 200 with mock data showing 25 habits"
echo ""

# Show current status
echo "CURRENT API STATUS:"
curl -s -w "HTTP Status: %{http_code}\n" -H "x-api-key: Y1leD4smWeX3yfCRM9Sv8R1Jo7g9zusx08Xo4y7o" "https://bhg1kt9cf2.execute-api.eu-central-1.amazonaws.com/prod/api/groups"

echo ""
echo "If still 502 after config changes, the Lambda logs will show the exact error."
