package org.isoron.uhabits.activities.analytics

import android.content.Context
import org.json.JSONObject
import java.io.File
import java.io.FileNotFoundException

/**
 * Secure configuration manager for cloud analytics
 * Handles API endpoints and keys without exposing AWS credentials
 */
object CloudConfig {
    
    private var config: JSONObject? = null
    private const val CONFIG_FILE = "android_config.json"
    private const val DEFAULT_ENDPOINT = "https://api.example.com/sync"
    
    /**
     * Load configuration from secure file
     */
    fun load(context: Context): Boolean {
        return try {
            val configFile = File(context.getExternalFilesDir(null), CONFIG_FILE)
            if (configFile.exists()) {
                val configText = configFile.readText()
                config = JSONObject(configText)
                true
            } else {
                // Create template for user
                createTemplate(context)
                false
            }
        } catch (e: Exception) {
            false
        }
    }
    
    /**
     * Get API endpoint URL
     */
    fun getApiEndpoint(): String {
        return config?.optString("api_endpoint", DEFAULT_ENDPOINT) ?: DEFAULT_ENDPOINT
    }
    
    /**
     * Get API key for authentication
     */
    fun getApiKey(): String? {
        return config?.optString("api_key")
    }
    
    /**
     * Get AWS region
     */
    fun getRegion(): String {
        return config?.optString("region", "us-east-1") ?: "us-east-1"
    }
    
    /**
     * Check if configuration is valid
     */
    fun isConfigured(): Boolean {
        return config != null && 
               !getApiKey().isNullOrEmpty() && 
               getApiEndpoint() != DEFAULT_ENDPOINT
    }
    
    /**
     * Get configuration status for UI
     */
    fun getConfigStatus(): String {
        return if (isConfigured()) {
            "✅ Cloud sync configured\n" +
            "Region: ${getRegion()}\n" +
            "Endpoint: ${getApiEndpoint().take(30)}..."
        } else {
            "⚠️  Cloud sync not configured\n" +
            "Run deployment script to generate config"
        }
    }
    
    /**
     * Create configuration template
     */
    private fun createTemplate(context: Context) {
        try {
            val template = JSONObject().apply {
                put("_instructions", "This file is generated by deploy_cloud_analytics.sh")
                put("_security_note", "This contains API Gateway keys, not AWS credentials")
                put("api_endpoint", "https://your-api-id.execute-api.region.amazonaws.com/prod/sync")
                put("api_key", "your-api-gateway-key-here")
                put("region", "us-east-1")
                put("environment", "prod")
            }
            
            val configFile = File(context.getExternalFilesDir(null), CONFIG_FILE)
            configFile.writeText(template.toString(2))
        } catch (e: Exception) {
            // Ignore template creation errors
        }
    }
}

/**
 * Usage in AnalyticsActivity:
 * 
 * if (CloudConfig.load(this)) {
 *     // Configuration loaded successfully
 *     syncToCloudAnalytics()
 * } else {
 *     // Show setup instructions
 *     showCloudSetupDialog()
 * }
 */
